Ignore generated files
LLNL/Quicksilver pull request #10
Opened 2017-11-10 22:08 UTC by connorimes

Git should ignore files generated during build.

2017-11-10 23:18 UTC, richards12 commented
Great minds think alike.  I committed a similar change earlier today in my local repo, but hadn't yet had time to make the pull request.

Before I can accept this, I'd like to request two changes:

1.  *.hh is too broad.  However, git_hash.hh and git_vers.hh are perfectly reasonable.
2. You probably also want to ignore .depend.bak.

If you'll make these two changes I'll accept the pull request.  Thanks for your interest in Quicksilver

2017-11-10 23:20 UTC, richards12 requested changes

2017-11-10 23:20 UTC, richards12 commented on .gitignore
> +*.hh
Too broad.  Please just git_hash.hh and git_vers.hh

2017-11-10 23:20 UTC, richards12 commented on .gitignore
> +.depend
.depend.bak too.

2017-11-11 03:20 UTC, connorimes commented
OK updated and rebased.  I didn't originally include `.depend.bak` or `load.map`, `*.core`, or `*.optrpt` since I didn't see where they were being created.  Should those also be included?

2017-11-12 15:47 UTC, richards12 approved these changes

2017-11-12 15:47 UTC, merged

2017-11-12 15:50 UTC, richards12 commented
.depend.bak is generated by makedepend.  The other files you mention are left-overs from some old build configurations that we deleted from the Makefile for simplicity.  There is no need to add them to the .gitignore file.

Thanks for your interest (and help) in Quicksilver.

2017-11-12 15:58 UTC, connorimes commented
You're welcome.  Those additional files/expressions can probably be removed from the `clean` target in the Makefile then as well.  Cheers.